version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask_app
    working_dir: /app
    command: gunicorn --bind 0.0.0.0:5001 wsgi:app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: celery_worker
    working_dir: /app
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"